local_conf_header:
  standard: |
    CONF_VERSION = "2"
    DL_DIR = "/workspace/downloads"
    PACKAGE_CLASSES = "package_rpm"
    SDKMACHINE = "x86_64"
    
  disk_space: |
    BB_DISKMON_DIRS = "\
        STOPTASKS,${TMPDIR},1G,100K \
        STOPTASKS,${DL_DIR},1G,100K \
        STOPTASKS,${SSTATE_DIR},1G,100K \
        STOPTASKS,/tmp,100M,100K \
        HALT,${TMPDIR},100M,1K \
        HALT,${DL_DIR},100M,1K \
        HALT,${SSTATE_DIR},100M,1K \
        HALT,/tmp,10M,1K"
    
  parallel: |
    # Adjust based on your build host
    BB_NUMBER_THREADS = "8"
    PARALLEL_MAKE = "-j 8"
